defaults:
  - _self_
  - paths: default.yaml
  - extras: default.yaml
  - hydra: default.yaml

  # task name, determines output directory path
task_name: "Remote_Switch"

# tags to help you identify your experiments
# you can overwrite this in experiment configs
# overwrite from command line with `python train.py tags="[first_tag, second_tag]"`
tags: ["dev"]